affected_purls:
- pkg:pypi/numpy@1.0
- pkg:pypi/numpy@1.3.0
- pkg:pypi/numpy@1.4.1
- pkg:pypi/numpy@1.5.0
- pkg:pypi/numpy@1.5.1
- pkg:pypi/numpy@1.6.0
- pkg:pypi/numpy@1.6.1
- pkg:pypi/numpy@1.6.2
- pkg:pypi/numpy@1.7.0
- pkg:pypi/numpy@1.7.1
- pkg:pypi/numpy@1.7.2
- pkg:pypi/numpy@1.8.0
aliases:
- CVE-2014-1859
- GHSA-2fc2-6r4j-p65h
fixed_purl:
- pkg:deb/debian/python-numpy@1:1.16.2-1?distro=buster
- pkg:deb/debian/python-numpy@1:1.8.1~rc1-1?distro=buster
- pkg:pypi/numpy@1.8.1
references:
- id: 136538
  reference_id: ''
  url: http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128358.html
- id: 136539
  reference_id: ''
  url: http://lists.fedoraproject.org/pipermail/package-announce/2014-February/128781.html
- id: 136535
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1062009
- id: 136545
  reference_id: ''
  url: https://exchange.xforce.ibmcloud.com/vulnerabilities/91317
- id: 136537
  reference_id: ''
  url: https://github.com/numpy/numpy/blob/maintenance/1.8.x/doc/release/1.8.1-notes.rst
- id: 136534
  reference_id: ''
  url: https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15
- id: 136533
  reference_id: ''
  url: https://github.com/numpy/numpy/pull/4262
- id: 136547
  reference_id: ''
  url: https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2018-34.yaml
- id: 136540
  reference_id: ''
  url: http://www.openwall.com/lists/oss-security/2014/02/08/3
- id: 136548
  reference_id: ''
  url: http://www.securityfocus.com/bid/65440
- id: 125339
  reference_id: '737778'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=737778
- id: 136544
  reference_id: CVE-2014-1859
  url: https://nvd.nist.gov/vuln/detail/CVE-2014-1859
- id: 136546
  reference_id: GHSA-2fc2-6r4j-p65h
  url: https://github.com/advisories/GHSA-2fc2-6r4j-p65h
severities:
- id: 18756
  reference_id: 136546
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: (1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py,
  and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to
  arbitrary files via a symlink attack on a temporary file.
vulnerability_id: VCID-9avd-5hnx-aaan
weaknesses: []
