affected_purls:
- pkg:pypi/django-s3file@0.1.0
- pkg:pypi/django-s3file@0.1.1
- pkg:pypi/django-s3file@0.1.10
- pkg:pypi/django-s3file@0.1.11
- pkg:pypi/django-s3file@0.1.12
- pkg:pypi/django-s3file@0.1.13
- pkg:pypi/django-s3file@0.1.14
- pkg:pypi/django-s3file@0.1.15
- pkg:pypi/django-s3file@0.1.16
- pkg:pypi/django-s3file@0.1.17
- pkg:pypi/django-s3file@0.1.18
- pkg:pypi/django-s3file@0.1.19
- pkg:pypi/django-s3file@0.1.2
- pkg:pypi/django-s3file@0.1.20
- pkg:pypi/django-s3file@0.1.21
- pkg:pypi/django-s3file@0.1.22
- pkg:pypi/django-s3file@0.1.23
- pkg:pypi/django-s3file@0.1.3
- pkg:pypi/django-s3file@0.1.4
- pkg:pypi/django-s3file@0.1.5
- pkg:pypi/django-s3file@0.1.6
- pkg:pypi/django-s3file@0.1.7
- pkg:pypi/django-s3file@0.1.8
- pkg:pypi/django-s3file@0.1.9
- pkg:pypi/django-s3file@0.2.0
- pkg:pypi/django-s3file@0.3.0
- pkg:pypi/django-s3file@0.3.1
- pkg:pypi/django-s3file@0.3.2
- pkg:pypi/django-s3file@0.3.3
- pkg:pypi/django-s3file@0.3.4
- pkg:pypi/django-s3file@0.3.5
- pkg:pypi/django-s3file@0.3.6
- pkg:pypi/django-s3file@0.3.7
- pkg:pypi/django-s3file@0.4.0
- pkg:pypi/django-s3file@0.4.1
- pkg:pypi/django-s3file@0.5.0
- pkg:pypi/django-s3file@0.5.1
- pkg:pypi/django-s3file@0.5.2
- pkg:pypi/django-s3file@0.5.3
- pkg:pypi/django-s3file@0.5.4
- pkg:pypi/django-s3file@0.6.0
- pkg:pypi/django-s3file@0.6.1
- pkg:pypi/django-s3file@0.6.2
- pkg:pypi/django-s3file@1.0.0
- pkg:pypi/django-s3file@1.0.1
- pkg:pypi/django-s3file@1.0.2
- pkg:pypi/django-s3file@1.1.0
- pkg:pypi/django-s3file@1.2.0
- pkg:pypi/django-s3file@1.2.1
- pkg:pypi/django-s3file@2.0.0
- pkg:pypi/django-s3file@3.0.0
- pkg:pypi/django-s3file@3.0.1
- pkg:pypi/django-s3file@3.0.2
- pkg:pypi/django-s3file@3.0.3
- pkg:pypi/django-s3file@3.0.4
- pkg:pypi/django-s3file@3.0.5
- pkg:pypi/django-s3file@4.0.0
- pkg:pypi/django-s3file@4.0.1
- pkg:pypi/django-s3file@4.0.2
- pkg:pypi/django-s3file@4.1.0
- pkg:pypi/django-s3file@4.2.0
- pkg:pypi/django-s3file@5.0.0
- pkg:pypi/django-s3file@5.0.1
- pkg:pypi/django-s3file@5.0.2
- pkg:pypi/django-s3file@5.0.4
- pkg:pypi/django-s3file@5.0.5
- pkg:pypi/django-s3file@5.0.6
- pkg:pypi/django-s3file@5.1.0
- pkg:pypi/django-s3file@5.1.1
- pkg:pypi/django-s3file@5.1.2
- pkg:pypi/django-s3file@5.1.3
- pkg:pypi/django-s3file@5.2.0
- pkg:pypi/django-s3file@5.3.0
- pkg:pypi/django-s3file@5.4.0
- pkg:pypi/django-s3file@5.5.0
aliases:
- CVE-2022-24840
- GHSA-4w8f-hjm9-xwgf
fixed_purl:
- pkg:pypi/django-s3file@5.5.1
references:
- id: 168256
  reference_id: ''
  url: https://github.com/codingjoe/django-s3file/commit/68ccd2c621a40eb66fdd6af2be9d5fcc9c373318
- id: 168257
  reference_id: ''
  url: https://github.com/codingjoe/django-s3file/releases/tag/5.5.1
- id: 168258
  reference_id: ''
  url: https://github.com/pypa/advisory-database/tree/main/vulns/django-s3file/PYSEC-2022-208.yaml
- id: 168255
  reference_id: CVE-2022-24840
  url: https://nvd.nist.gov/vuln/detail/CVE-2022-24840
- id: 168259
  reference_id: GHSA-4w8f-hjm9-xwgf
  url: https://github.com/advisories/GHSA-4w8f-hjm9-xwgf
- id: 168254
  reference_id: GHSA-4w8f-hjm9-xwgf
  url: https://github.com/codingjoe/django-s3file/security/advisories/GHSA-4w8f-hjm9-xwgf
severities:
- id: 25705
  reference_id: 168259
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: CRITICAL
- id: 25704
  reference_id: 168254
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: CRITICAL
summary: Path Traversal in django-s3file
vulnerability_id: VCID-duj3-t4qr-aaad
weaknesses: []
