affected_purls:
- pkg:deb/debian/python-ldap@3.1.0-2
- pkg:deb/debian/python-ldap@3.2.0-4
- pkg:pypi/python-ldap@2.3.13
- pkg:pypi/python-ldap@2.4.0
- pkg:pypi/python-ldap@2.4.1
- pkg:pypi/python-ldap@2.4.10
- pkg:pypi/python-ldap@2.4.12
- pkg:pypi/python-ldap@2.4.13
- pkg:pypi/python-ldap@2.4.14
- pkg:pypi/python-ldap@2.4.15
- pkg:pypi/python-ldap@2.4.16
- pkg:pypi/python-ldap@2.4.17
- pkg:pypi/python-ldap@2.4.18
- pkg:pypi/python-ldap@2.4.19
- pkg:pypi/python-ldap@2.4.2
- pkg:pypi/python-ldap@2.4.20
- pkg:pypi/python-ldap@2.4.21
- pkg:pypi/python-ldap@2.4.22
- pkg:pypi/python-ldap@2.4.25
- pkg:pypi/python-ldap@2.4.26
- pkg:pypi/python-ldap@2.4.27
- pkg:pypi/python-ldap@2.4.28
- pkg:pypi/python-ldap@2.4.29
- pkg:pypi/python-ldap@2.4.3
- pkg:pypi/python-ldap@2.4.30
- pkg:pypi/python-ldap@2.4.31
- pkg:pypi/python-ldap@2.4.32
- pkg:pypi/python-ldap@2.4.33
- pkg:pypi/python-ldap@2.4.35
- pkg:pypi/python-ldap@2.4.36
- pkg:pypi/python-ldap@2.4.37
- pkg:pypi/python-ldap@2.4.38
- pkg:pypi/python-ldap@2.4.39
- pkg:pypi/python-ldap@2.4.4
- pkg:pypi/python-ldap@2.4.40
- pkg:pypi/python-ldap@2.4.41
- pkg:pypi/python-ldap@2.4.42
- pkg:pypi/python-ldap@2.4.43
- pkg:pypi/python-ldap@2.4.44
- pkg:pypi/python-ldap@2.4.45
- pkg:pypi/python-ldap@2.4.5
- pkg:pypi/python-ldap@2.4.6
- pkg:pypi/python-ldap@2.4.7
- pkg:pypi/python-ldap@2.4.8
- pkg:pypi/python-ldap@2.4.9
- pkg:pypi/python-ldap@2.5.1
- pkg:pypi/python-ldap@2.5.2
- pkg:pypi/python-ldap@3.0.0
- pkg:pypi/python-ldap@3.0.0b1
- pkg:pypi/python-ldap@3.0.0b2
- pkg:pypi/python-ldap@3.0.0b3
- pkg:pypi/python-ldap@3.0.0b4
- pkg:pypi/python-ldap@3.1.0
- pkg:pypi/python-ldap@3.2.0
- pkg:pypi/python-ldap@3.3.0
- pkg:pypi/python-ldap@3.3.1
aliases:
- CVE-2021-46823
- GHSA-qfr5-wjpw-q4c4
fixed_purl:
- pkg:deb/debian/python-ldap@3.4.3-2
- pkg:pypi/python-ldap@3.4.0
references:
- id: 165090
  reference_id: ''
  url: https://exchange.xforce.ibmcloud.com/vulnerabilities/221507
- id: 165089
  reference_id: CVE-2021-46823
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-46823
- id: 165091
  reference_id: GHSA-qfr5-wjpw-q4c4
  url: https://github.com/advisories/GHSA-qfr5-wjpw-q4c4
- id: 132731
  reference_id: GHSA-r8wq-qrxc-hmcm
  url: https://github.com/python-ldap/python-ldap/security/advisories/GHSA-r8wq-qrxc-hmcm
severities:
- id: 24824
  reference_id: 165091
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
- id: 18112
  reference_id: 132731
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: Denial of Service in python-ldap
vulnerability_id: VCID-zux9-edpe-aaak
weaknesses: []
