affected_purls:
- pkg:deb/debian/pillow@5.4.1-2%2Bdeb10u3
- pkg:pypi/pillow@1.0
- pkg:pypi/pillow@1.1
- pkg:pypi/pillow@1.2
- pkg:pypi/pillow@1.3
- pkg:pypi/pillow@1.4
- pkg:pypi/pillow@1.5
- pkg:pypi/pillow@1.6
- pkg:pypi/pillow@1.7.0
- pkg:pypi/pillow@1.7.1
- pkg:pypi/pillow@1.7.2
- pkg:pypi/pillow@1.7.3
- pkg:pypi/pillow@1.7.4
- pkg:pypi/pillow@1.7.5
- pkg:pypi/pillow@1.7.6
- pkg:pypi/pillow@1.7.7
- pkg:pypi/pillow@1.7.8
- pkg:pypi/pillow@2.0.0
- pkg:pypi/pillow@2.1.0
- pkg:pypi/pillow@2.2.0
- pkg:pypi/pillow@2.2.1
- pkg:pypi/pillow@2.2.2
- pkg:pypi/pillow@2.3.0
- pkg:pypi/pillow@2.3.1
- pkg:pypi/pillow@2.3.2
- pkg:pypi/pillow@2.4.0
- pkg:pypi/pillow@2.5.0
- pkg:pypi/pillow@2.5.1
- pkg:pypi/pillow@2.5.2
- pkg:pypi/pillow@2.5.3
- pkg:pypi/pillow@2.6.0
- pkg:pypi/pillow@2.6.1
- pkg:pypi/pillow@2.6.2
- pkg:pypi/pillow@2.7.0
- pkg:pypi/pillow@2.8.0
- pkg:pypi/pillow@2.8.1
- pkg:pypi/pillow@2.8.2
- pkg:pypi/pillow@2.9.0
- pkg:pypi/pillow@3.0.0
- pkg:pypi/pillow@3.1.0
- pkg:pypi/pillow@3.1.0.rc1
- pkg:pypi/pillow@3.1.0rc1
- pkg:pypi/pillow@3.1.1
- pkg:pypi/pillow@3.1.2
- pkg:pypi/pillow@3.2.0
- pkg:pypi/pillow@3.3.0
- pkg:pypi/pillow@3.3.1
- pkg:pypi/pillow@3.3.2
- pkg:pypi/pillow@3.3.3
- pkg:pypi/pillow@3.4.0
- pkg:pypi/pillow@3.4.1
- pkg:pypi/pillow@3.4.2
- pkg:pypi/pillow@4.0.0
- pkg:pypi/pillow@4.1.0
- pkg:pypi/pillow@4.1.1
- pkg:pypi/pillow@4.2.0
- pkg:pypi/pillow@4.2.1
- pkg:pypi/pillow@4.3.0
- pkg:pypi/pillow@5.0.0
- pkg:pypi/pillow@5.1.0
- pkg:pypi/pillow@5.2.0
- pkg:pypi/pillow@5.3.0
- pkg:pypi/pillow@5.4.0
- pkg:pypi/pillow@5.4.0.dev0
- pkg:pypi/pillow@5.4.1
- pkg:pypi/pillow@6.0.0
- pkg:pypi/pillow@6.1.0
- pkg:pypi/pillow@6.2.0
- pkg:pypi/pillow@6.2.1
- pkg:pypi/pillow@6.2.2
- pkg:pypi/pillow@7.0.0
- pkg:pypi/pillow@7.1.0
- pkg:pypi/pillow@7.1.1
- pkg:pypi/pillow@7.1.2
- pkg:pypi/pillow@7.2.0
- pkg:pypi/pillow@8.0.0
- pkg:pypi/pillow@8.0.1
- pkg:pypi/pillow@8.1.0
- pkg:pypi/pillow@8.1.1
- pkg:pypi/pillow@8.1.2
aliases:
- CVE-2021-28676
- GHSA-7r7m-5h27-29hp
fixed_purl:
- pkg:deb/debian/pillow@8.1.2%2Bdfsg-0.3%2Bdeb11u1
- pkg:pypi/pillow@8.2.0
references:
- id: 159556
  reference_id: ''
  url: https://github.com/python-pillow/Pillow/pull/5377
- id: 154340
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2021/07/msg00018.html
- id: 158641
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/
- id: 159557
  reference_id: ''
  url: https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos
- id: 158642
  reference_id: ''
  url: https://security.gentoo.org/glsa/202107-33
- id: 129682
  reference_id: '989062'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989062
- id: 159555
  reference_id: CVE-2021-28676
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-28676
- id: 159558
  reference_id: GHSA-7r7m-5h27-29hp
  url: https://github.com/advisories/GHSA-7r7m-5h27-29hp
severities:
- id: 23217
  reference_id: 159558
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did
  not properly check that the block advance was non-zero, potentially leading to an
  infinite loop on load.
vulnerability_id: VCID-mxyv-6frq-aaar
weaknesses: []
