affected_purls:
- pkg:pypi/pyyaml@5.1
- pkg:pypi/pyyaml@5.1.1
- pkg:pypi/pyyaml@5.1.2
- pkg:pypi/pyyaml@5.2b1
aliases:
- CVE-2019-20477
- GHSA-3pqx-4fqf-j49f
fixed_purl:
- pkg:deb/debian/pyyaml@0?distro=sid
- pkg:deb/debian/pyyaml@3.13-2?distro=sid
- pkg:deb/debian/pyyaml@5.2-1?distro=sid
- pkg:deb/debian/pyyaml@5.3.1-5?distro=sid
- pkg:deb/debian/pyyaml@6.0-3?distro=sid
- pkg:pypi/pyyaml@5.2
references:
- id: 142178
  reference_id: ''
  url: https://github.com/yaml/pyyaml/blob/master/CHANGES
- id: 149247
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/33VBUY73AA6CTTYL3LRWHNFDULV7PFPN/
- id: 149248
  reference_id: ''
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/52N5XS73Z5S4ZN7I7R56ICCPCTKCUV4H/
- id: 149249
  reference_id: ''
  url: https://www.exploit-db.com/download/47655
- id: 149246
  reference_id: CVE-2019-20477
  url: https://nvd.nist.gov/vuln/detail/CVE-2019-20477
- id: 149250
  reference_id: GHSA-3pqx-4fqf-j49f
  url: https://github.com/advisories/GHSA-3pqx-4fqf-j49f
severities:
- id: 21052
  reference_id: 149250
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: 'PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all
  functions because of a class deserialization issue, e.g., Popen is a class in the
  subprocess module. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342.'
vulnerability_id: VCID-8mp8-9sgw-aaah
weaknesses: []
