affected_purls:
- pkg:pypi/dparse@0.1.0
- pkg:pypi/dparse@0.1.1
- pkg:pypi/dparse@0.2.0
- pkg:pypi/dparse@0.2.1
- pkg:pypi/dparse@0.3.0
- pkg:pypi/dparse@0.4.0
- pkg:pypi/dparse@0.4.1
- pkg:pypi/dparse@0.5.0
- pkg:pypi/dparse@0.5.1
aliases:
- CVE-2022-39280
- GHSA-8fg9-p83m-x5pq
fixed_purl:
- pkg:pypi/dparse@0.5.2
references:
- id: 172217
  reference_id: ''
  url: https://github.com/pypa/advisory-database/tree/main/vulns/dparse/PYSEC-2022-301.yaml
- id: 172213
  reference_id: ''
  url: https://github.com/pyupio/dparse/commit/8c990170bbd6c0cf212f1151e9025486556062d5
- id: 172214
  reference_id: ''
  url: https://github.com/pyupio/dparse/commit/d87364f9db9ab916451b1b036cfeb039e726e614
- id: 172215
  reference_id: ''
  url: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS
- id: 172216
  reference_id: CVE-2022-39280
  url: https://nvd.nist.gov/vuln/detail/CVE-2022-39280
- id: 172218
  reference_id: GHSA-8fg9-p83m-x5pq
  url: https://github.com/advisories/GHSA-8fg9-p83m-x5pq
- id: 172212
  reference_id: GHSA-8fg9-p83m-x5pq
  url: https://github.com/pyupio/dparse/security/advisories/GHSA-8fg9-p83m-x5pq
severities:
- id: 26807
  reference_id: 172218
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
- id: 26806
  reference_id: 172212
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: ReDoS issue in dparse
vulnerability_id: VCID-2rj4-4fyg-aaac
weaknesses: []
