affected_purls:
- pkg:pypi/opencv-contrib-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.7
- pkg:pypi/opencv-python@3.2.0.8
- pkg:pypi/opencv-python@3.3.0.9
aliases:
- CVE-2017-12863
- GHSA-wq8f-wvqp-xvvm
fixed_purl:
- pkg:deb/debian/opencv@3.2.0%2Bdfsg-6?distro=sid
- pkg:deb/debian/opencv@4.5.1%2Bdfsg-5?distro=sid
- pkg:deb/debian/opencv@4.6.0%2Bdfsg-12?distro=sid
- pkg:pypi/opencv-contrib-python@3.3.0.10
- pkg:pypi/opencv-python@3.3.0.10
references:
- id: 140957
  reference_id: ''
  url: https://github.com/opencv/opencv/issues/9371
- id: 139477
  reference_id: ''
  url: https://github.com/opencv/opencv/pull/9376
- id: 139476
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2018/07/msg00030.html
- id: 139478
  reference_id: ''
  url: https://lists.debian.org/debian-lts-announce/2021/10/msg00028.html
- id: 140784
  reference_id: ''
  url: https://security.gentoo.org/glsa/201712-02
- id: 126877
  reference_id: '875344'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875344
- id: 140956
  reference_id: CVE-2017-12863
  url: https://nvd.nist.gov/vuln/detail/CVE-2017-12863
- id: 140958
  reference_id: GHSA-wq8f-wvqp-xvvm
  url: https://github.com/advisories/GHSA-wq8f-wvqp-xvvm
severities:
- id: 19515
  reference_id: 140958
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData
  has an integer overflow when calculate src_pitch. If the image is from remote, may
  lead to remote code execution or denial of service. This affects Opencv 3.3 and
  earlier.
vulnerability_id: VCID-dma1-ug88-aaaq
weaknesses: []
