affected_purls:
- pkg:pypi/jupyterhub-firstuseauthenticator@0.10
- pkg:pypi/jupyterhub-firstuseauthenticator@0.11
- pkg:pypi/jupyterhub-firstuseauthenticator@0.12
- pkg:pypi/jupyterhub-firstuseauthenticator@0.13.0
- pkg:pypi/jupyterhub-firstuseauthenticator@0.14.0
- pkg:pypi/jupyterhub-firstuseauthenticator@0.14.1
- pkg:pypi/jupyterhub-firstuseauthenticator@0.9
aliases:
- CVE-2021-41194
- GHSA-5xvc-vgmp-jgc3
fixed_purl:
- pkg:pypi/jupyterhub-firstuseauthenticator@1.0.0
references:
- id: 163623
  reference_id: ''
  url: https://github.com/jupyterhub/firstuseauthenticator/pull/38
- id: 163625
  reference_id: ''
  url: https://github.com/jupyterhub/firstuseauthenticator/pull/38/commits/32b21898fb2b53b1a2e36270de6854ad70e9e9bf
- id: 163626
  reference_id: ''
  url: https://github.com/jupyterhub/firstuseauthenticator/pull/38/commits/9e200d974e0cb85d828a6afedb8ab90a37878f28
- id: 163624
  reference_id: ''
  url: https://github.com/jupyterhub/firstuseauthenticator/pull/38.patch
- id: 163622
  reference_id: CVE-2021-41194
  url: https://nvd.nist.gov/vuln/detail/CVE-2021-41194
- id: 163627
  reference_id: GHSA-5xvc-vgmp-jgc3
  url: https://github.com/advisories/GHSA-5xvc-vgmp-jgc3
- id: 163621
  reference_id: GHSA-5xvc-vgmp-jgc3
  url: https://github.com/jupyterhub/firstuseauthenticator/security/advisories/GHSA-5xvc-vgmp-jgc3
severities:
- id: 24441
  reference_id: 163627
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: CRITICAL
- id: 24440
  reference_id: 163621
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: CRITICAL
summary: Improper Access Control in jupyterhub-firstuseauthenticator
vulnerability_id: VCID-wcb1-926a-aaac
weaknesses: []
