affected_purls:
- pkg:pypi/ansible@2.0.0.0
- pkg:pypi/ansible@2.4.0.0
- pkg:pypi/ansible@2.4.1.0
- pkg:pypi/ansible@2.4.2.0
- pkg:pypi/ansible@2.4.3.0
- pkg:pypi/ansible@2.4.4.0
- pkg:pypi/ansible@2.5.0
- pkg:pypi/ansible@2.5.1
- pkg:pypi/ansible@2.5.2
- pkg:pypi/ansible@2.5.3
- pkg:pypi/ansible@2.5.4
aliases:
- CVE-2018-10855
- GHSA-jwcc-j78w-j73w
fixed_purl:
- pkg:deb/debian/ansible@2.10.7%2Bmerged%2Bbase%2B2.10.8%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.5.5%2Bdfsg-1?distro=sid
- pkg:deb/debian/ansible@2.7.7%2Bdfsg-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/ansible@7.3.0%2Bdfsg-1?distro=sid
- pkg:pypi/ansible@2.0.0.1
- pkg:pypi/ansible@2.4.5.0
- pkg:pypi/ansible@2.5.5
- pkg:pypi/ansible@2.6.0a1
references:
- id: 143677
  reference_id: ''
  url: https://access.redhat.com/errata/RHBA-2018:3788
- id: 143678
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2018:1948
- id: 143679
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2018:1949
- id: 143680
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2018:2022
- id: 143681
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2018:2079
- id: 143682
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2018:2184
- id: 143683
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2018:2585
- id: 143684
  reference_id: ''
  url: https://access.redhat.com/errata/RHSA-2019:0054
- id: 143685
  reference_id: ''
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10855
- id: 143687
  reference_id: ''
  url: https://usn.ubuntu.com/4072-1/
- id: 143688
  reference_id: ''
  url: https://www.debian.org/security/2019/dsa-4396
- id: 143676
  reference_id: CVE-2018-10855
  url: https://nvd.nist.gov/vuln/detail/CVE-2018-10855
- id: 143686
  reference_id: GHSA-jwcc-j78w-j73w
  url: https://github.com/advisories/GHSA-jwcc-j78w-j73w
severities:
- id: 20045
  reference_id: 143686
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: Ansible 2.5 prior to 2.5.5, and 2.4 prior to 2.4.5, do not honor the no_log
  task flag for failed tasks. When the no_log flag has been used to protect sensitive
  data passed to a task from being logged, and that task does not run successfully,
  Ansible will expose sensitive data in log files and on the terminal of the user
  running Ansible.
vulnerability_id: VCID-wc7t-7kry-aaah
weaknesses: []
