affected_purls:
- pkg:pypi/django@1.9
- pkg:pypi/django@1.9.1
- pkg:pypi/django@1.9a1
- pkg:pypi/django@1.9b1
- pkg:pypi/django@1.9rc1
- pkg:pypi/django@1.9rc2
aliases:
- CVE-2016-2048
fixed_purl:
- pkg:deb/debian/python-django@1:1.11.29-1~deb10u1?distro=sid
- pkg:deb/debian/python-django@1.9.2-1?distro=sid
- pkg:deb/debian/python-django@2:2.2.28-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@3:3.2.19-1?distro=sid
- pkg:pypi/django@1.9.2
references:
- id: 177589
  reference_id: ''
  url: https://www.djangoproject.com/weblog/2016/feb/01/releases-192-and-189/
- id: 126191
  reference_id: '813448'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813448
severities: []
summary: Django 1.9.x before 1.9.2, when ModelAdmin.save_as is set to True, allows
  remote authenticated users to bypass intended access restrictions and create ModelAdmin
  objects via the "Save as New" option when editing objects and leveraging the "change"
  permission.
vulnerability_id: VCID-yrby-ky7e-aaan
weaknesses: []
