affected_purls:
- pkg:pypi/django@1.8
- pkg:pypi/django@1.8.1
- pkg:pypi/django@1.8.2
- pkg:pypi/django@1.8.3
- pkg:pypi/django@1.8.4
- pkg:pypi/django@1.8.5
- pkg:pypi/django@1.8.6
- pkg:pypi/django@1.8.7
- pkg:pypi/django@1.8.8
- pkg:pypi/django@1.8.9
- pkg:pypi/django@1.8a1
- pkg:pypi/django@1.8b1
- pkg:pypi/django@1.8b2
- pkg:pypi/django@1.8c1
- pkg:pypi/django@1.9
- pkg:pypi/django@1.9.1
- pkg:pypi/django@1.9.2
- pkg:pypi/django@1.9a1
- pkg:pypi/django@1.9b1
- pkg:pypi/django@1.9rc1
- pkg:pypi/django@1.9rc2
aliases:
- CVE-2016-2512
fixed_purl:
- pkg:deb/debian/python-django@1:1.11.29-1~deb10u1?distro=sid
- pkg:deb/debian/python-django@1.9.4-1?distro=sid
- pkg:deb/debian/python-django@2:2.2.28-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@3:3.2.19-1?distro=sid
- pkg:pypi/django@1.8.10
- pkg:pypi/django@1.9.3
references:
- id: 177610
  reference_id: ''
  url: https://www.djangoproject.com/weblog/2016/mar/01/security-releases/
- id: 126219
  reference_id: '816434'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816434
severities: []
summary: The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before
  1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct
  phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL
  containing basic authentication, as demonstrated by http://mysite.example.com\@attacker.com.
vulnerability_id: VCID-1dxw-56um-aaaj
weaknesses: []
