affected_purls:
- pkg:pypi/django@1.11.8
- pkg:pypi/django@1.11.9
- pkg:pypi/django@2.0
- pkg:pypi/django@2.0.1
aliases:
- CVE-2018-6188
- GHSA-rf4j-j272-fj86
fixed_purl:
- pkg:deb/debian/python-django@1:1.11.10-1?distro=sid
- pkg:deb/debian/python-django@1:1.11.29-1~deb10u1?distro=sid
- pkg:deb/debian/python-django@2:2.2.28-1~deb11u1?distro=sid
- pkg:deb/debian/python-django@3:3.2.19-1?distro=sid
- pkg:pypi/django@1.11.10
- pkg:pypi/django@2.0.2
references:
- id: 140943
  reference_id: ''
  url: https://usn.ubuntu.com/3559-1/
- id: 145491
  reference_id: ''
  url: https://www.djangoproject.com/weblog/2018/feb/01/security-releases/
- id: 145492
  reference_id: ''
  url: http://www.securitytracker.com/id/1040422
- id: 145489
  reference_id: CVE-2018-6188
  url: https://nvd.nist.gov/vuln/detail/CVE-2018-6188
- id: 145490
  reference_id: GHSA-rf4j-j272-fj86
  url: https://github.com/advisories/GHSA-rf4j-j272-fj86
severities:
- id: 20414
  reference_id: 145490
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: django.contrib.auth.forms.AuthenticationForm in Django 2.0 before 2.0.2,
  and 1.11.8 and 1.11.9, allows remote attackers to obtain potentially sensitive information
  by leveraging data exposure from the confirm_login_allowed() method, as demonstrated
  by discovering whether a user account is inactive.
vulnerability_id: VCID-5ear-fmec-aaag
weaknesses: []
