affected_purls:
- pkg:pypi/flask-cors@1.0
- pkg:pypi/flask-cors@1.1
- pkg:pypi/flask-cors@1.10.0
- pkg:pypi/flask-cors@1.10.1
- pkg:pypi/flask-cors@1.10.2
- pkg:pypi/flask-cors@1.10.3
- pkg:pypi/flask-cors@1.1.1
- pkg:pypi/flask-cors@1.1.2
- pkg:pypi/flask-cors@1.1.3
- pkg:pypi/flask-cors@1.2.0
- pkg:pypi/flask-cors@1.2.1
- pkg:pypi/flask-cors@1.3.0
- pkg:pypi/flask-cors@1.3.1
- pkg:pypi/flask-cors@1.4.0
- pkg:pypi/flask-cors@1.5.0
- pkg:pypi/flask-cors@1.6.0
- pkg:pypi/flask-cors@1.6.1
- pkg:pypi/flask-cors@1.7.0
- pkg:pypi/flask-cors@1.7.1
- pkg:pypi/flask-cors@1.7.2
- pkg:pypi/flask-cors@1.7.3
- pkg:pypi/flask-cors@1.7.4
- pkg:pypi/flask-cors@1.8.0
- pkg:pypi/flask-cors@1.8.1
- pkg:pypi/flask-cors@1.9.0
- pkg:pypi/flask-cors@2.0.0
- pkg:pypi/flask-cors@2.0.0rc1
- pkg:pypi/flask-cors@2.0.1
- pkg:pypi/flask-cors@2.1.0
- pkg:pypi/flask-cors@2.1.1
- pkg:pypi/flask-cors@2.1.2
- pkg:pypi/flask-cors@2.1.3
- pkg:pypi/flask-cors@3.0.0
- pkg:pypi/flask-cors@3.0.1
- pkg:pypi/flask-cors@3.0.2
- pkg:pypi/flask-cors@3.0.3
- pkg:pypi/flask-cors@3.0.4
- pkg:pypi/flask-cors@3.0.6
- pkg:pypi/flask-cors@3.0.7
- pkg:pypi/flask-cors@3.0.8
aliases:
- CVE-2020-25032
- GHSA-xc3p-ff3m-f46v
fixed_purl:
- pkg:deb/debian/python-flask-cors@3.0.10-2?distro=sid
- pkg:deb/debian/python-flask-cors@3.0.7-1%2Bdeb10u1?distro=sid
- pkg:deb/debian/python-flask-cors@3.0.9-1?distro=sid
- pkg:deb/debian/python-flask-cors@3.0.9-2?distro=sid
- pkg:pypi/flask-cors@3.0.9
references:
- id: 152787
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00028.html
- id: 152788
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00032.html
- id: 152789
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00039.html
- id: 152790
  reference_id: ''
  url: http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00048.html
- id: 152784
  reference_id: ''
  url: https://github.com/corydolphin/flask-cors/commit/67c4b2cc98ae87cf1fa7df4f97fd81b40c79b895
- id: 152785
  reference_id: ''
  url: https://github.com/corydolphin/flask-cors/releases/tag/3.0.9
- id: 152786
  reference_id: ''
  url: https://www.debian.org/security/2020/dsa-4775
- id: 129293
  reference_id: '969362'
  url: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=969362
- id: 152783
  reference_id: CVE-2020-25032
  url: https://nvd.nist.gov/vuln/detail/CVE-2020-25032
- id: 152791
  reference_id: GHSA-xc3p-ff3m-f46v
  url: https://github.com/advisories/GHSA-xc3p-ff3m-f46v
severities:
- id: 21815
  reference_id: 152791
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: HIGH
summary: An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before
  3.0.9. It allows ../ directory traversal to access private resources because resource
  matching does not ensure that pathnames are in a canonical format.
vulnerability_id: VCID-e1mu-6wda-aaaj
weaknesses: []
