affected_purls:
- pkg:deb/debian/pypy3@7.0.0%2Bdfsg-3
aliases:
- CVE-2021-3426
fixed_purl:
- pkg:deb/debian/pypy3@7.3.5%2Bdfsg-2%2Bdeb11u2
- pkg:deb/debian/python2.7@0?distro=buster
- pkg:deb/debian/python2.7@2.7.16-2%2Bdeb10u1?distro=buster
- pkg:deb/debian/python2.7@2.7.18-8?distro=buster
references: []
severities: []
summary: There's a flaw in Python 3's pydoc. A local or adjacent attacker who discovers
  or is able to convince another local or adjacent user to start a pydoc server could
  access the server and use it to disclose sensitive information belonging to the
  other user that they would not normally be able to access. The highest risk of this
  flaw is to data confidentiality. This flaw affects Python versions before 3.8.9,
  Python versions before 3.9.3 and Python versions before 3.10.0a7.
vulnerability_id: VCID-r62m-9npj-aaah
weaknesses: []
