affected_purls:
- pkg:pypi/redis@4.2.0
- pkg:pypi/redis@4.2.1
- pkg:pypi/redis@4.2.2
- pkg:pypi/redis@4.3.0
- pkg:pypi/redis@4.3.1
- pkg:pypi/redis@4.3.2
- pkg:pypi/redis@4.3.3
- pkg:pypi/redis@4.3.4
- pkg:pypi/redis@4.3.5
- pkg:pypi/redis@4.3.6
- pkg:pypi/redis@4.4.0
- pkg:pypi/redis@4.4.0rc1
- pkg:pypi/redis@4.4.0rc2
- pkg:pypi/redis@4.4.0rc3
- pkg:pypi/redis@4.4.0rc4
- pkg:pypi/redis@4.4.1
- pkg:pypi/redis@4.4.2
- pkg:pypi/redis@4.4.3
- pkg:pypi/redis@4.5.0
- pkg:pypi/redis@4.5.1
- pkg:pypi/redis@4.5.2
- pkg:pypi/redis@4.5.3
aliases:
- CVE-2023-28859
- GHSA-8fww-64cx-x8p5
fixed_purl:
- pkg:pypi/redis@5.0.0b1
references:
- id: 176245
  reference_id: ''
  url: https://github.com/pypa/advisory-database/tree/main/vulns/redis/PYSEC-2023-46.yaml
- id: 176242
  reference_id: ''
  url: https://github.com/redis/redis-py/issues/2665
- id: 176246
  reference_id: ''
  url: https://github.com/redis/redis-py/pull/1899
- id: 176233
  reference_id: ''
  url: https://github.com/redis/redis-py/pull/2641
- id: 176243
  reference_id: ''
  url: https://github.com/redis/redis-py/pull/2666
- id: 176244
  reference_id: ''
  url: https://github.com/redis/redis-py/pull/2671
- id: 176238
  reference_id: ''
  url: https://github.com/redis/redis-py/releases/tag/v4.4.4
- id: 176239
  reference_id: ''
  url: https://github.com/redis/redis-py/releases/tag/v4.5.4
- id: 176241
  reference_id: CVE-2023-28859
  url: https://nvd.nist.gov/vuln/detail/CVE-2023-28859
- id: 176247
  reference_id: GHSA-8fww-64cx-x8p5
  url: https://github.com/advisories/GHSA-8fww-64cx-x8p5
severities:
- id: 27945
  reference_id: 176247
  scoring_elements: ''
  scoring_system: cvssv3.1_qr
  value: MODERATE
summary: redis-py Race Condition due to incomplete fix
vulnerability_id: VCID-buhm-wbs6-aaab
weaknesses: []
